### ISSUE TITLE
Canali da verificare 

### ISSUE THREAD

**Issue by samuele1979** [kodiondemand/kodiondemand.github.io#4]
Anime e serie japponesi tipo megaloman
https://blog.libero.it/wp/animehousezone/
https://www.greatanimation.org/
https://www.subranger.it/download-choujin-sentai-jetman/
https://www.animehdita.org/
Serie TV e film (sezione)
https://www.downloadme.gratis/
https://hd4me.net/
https://marapcana.store/
https://verystream.it/
https://film4k.link/
https://cinefun.co/
https://filmsenzalimiti.kim/
https://guardare.film/
https://streamingsenzalimiti.net/
https://guardoserie.net/
https://dragonfx1234.wixsite.com/openmovies/
https://cinemahd.work/
https://vedigratis.com/

**Comment by mac12m99** [comment]
Grazie della lista, vedremo se c'è qualche sito per cui ne vale la pena!
PS
la prossima volta, apri sul repo "addon", purtroppo ce ne siamo accorti solo ora perchè non monitoriamo questo repo..
