### ISSUE TITLE
Fix ricerca ilgediodellostreaming 

### ISSUE THREAD

**Issue by victor0338** [kodiondemand/kodiondemand.github.io#5]
Ciao, da qualche giorno il "cerca" globale Serie tv/film non funziona o meglio la ricerca da nessun elemento trovato.
Ho eseguito la stessa ricerca su loro sito web e funziona. Probabile filtro Firewall DDos protection di Cloudflare, oppure cambio struttura da fixare.

**Comment by mac12m99** [comment]
Ciao, mi spiace ma hai l'aperto l'issue sul repo sbagliato e non ce ne siamo accorti :(
La prossima volta apri su "addon".

Comunque questo è un problema ricorrente causa DDos protection di Cloudflare, come hai giustamente indicato.
